=== davitp/tracking-software/trunk/TrackingSoftware/AccessLayer/MappingResources/SQLUnitMapping/OperationsMapperSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">
  <xs:element name="Unit">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Operation" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="CommandType" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="StoredProcedure"/>
                    <xs:enumeration value="Text"/>
                    <xs:enumeration value="TableDirect"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element type="xs:string" name="CommandText" minOccurs="1" maxOccurs="1" />
              <xs:element  name="ReturnType"  minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Set"/>
                    <xs:enumeration value="Scalar"/>
                    <xs:enumeration value="NonQuery"/>
                    <xs:enumeration value="Update" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Parameters" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Add" minOccurs="1">
                      <xs:complexType>

                         <xs:attribute name="DbType" use="required" >
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="BigInt" />
                              <xs:enumeration value="Binary" />
                              <xs:enumeration value="Bit" />
                              <xs:enumeration value="Char" />
                              <xs:enumeration value="Date" />
                              <xs:enumeration value="DateTime" />
                              <xs:enumeration value="DateTimeWithTimeZone" />
                              <xs:enumeration value="Decimal" />
                              <xs:enumeration value="Float" />
                              <xs:enumeration value="Image" />
                              <xs:enumeration value="Int" />
                              <xs:enumeration value="LargeDateTime" />
                              <xs:enumeration value="Money" />
                              <xs:enumeration value="NChar" />
                              <xs:enumeration value="NText" />
                              <xs:enumeration value="NVarChar" />
                              <xs:enumeration value="Real" />
                              <xs:enumeration value="SmallDateTime" />
                              <xs:enumeration value="SmallInt" />
                              <xs:enumeration value="SmallMoney" />
                              <xs:enumeration value="Text" />
                              <xs:enumeration value="Time" />
                              <xs:enumeration value="Timestamp" />
                              <xs:enumeration value="TinyInt" />
                              <xs:enumeration value="Udt" />
                              <xs:enumeration value="UniqueIdentifier" />
                              <xs:enumeration value="VarBinary" />
                              <xs:enumeration value="VarChar" />
                              <xs:enumeration value="Variant" />
                              <xs:enumeration value="Xml" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                   
                        <xs:attribute name="ParamSize" />
                        <xs:attribute name="Name" use="required"/>


                      </xs:complexType>
                      
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="Name" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="UnitName" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== davitp/tracking-software/TrackingSoftware/AccessLayer/MappingResources/SQLUnitMapping/carState_operations.xml
<?xml version="1.0" encoding="utf-8" ?>
<Unit UnitName="car" xmlns="http://www.w3schools.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.w3schools.com OperationsMapperSchema.xsd">
  
  <!-- Get last known state operation -->
  <Operation Name="GetLastState">
    <CommandType>Text</CommandType>
    <CommandText>
      select top 1
      fuelLevel, speed, changeOil,
      latitude, longitude, stateTime
      from carsState_table
      where
      carId = @id
      order by stateTime desc
      )

    </CommandText>
    <ReturnType>Set</ReturnType>
    <Parameters>
      <Add DbType="Int" Name="id" />
    </Parameters>
  </Operation>

  <!-- Get state history of car in interval -->
  <Operation Name="GetStateHistory">
    <CommandType>Text</CommandType>
    <CommandText>
      select 
      fuelLevel, speed, changeOil,
      latitude, longitude, stateTime
      from carsState_table
      where
      carId = @id
      and stateTime between @start and @end
      order by stateTime
      

    </CommandText>
    <ReturnType>Set</ReturnType>
    <Parameters>
      <Add DbType="Int" Name="id" />
      <Add DbType="DateTime" Name="start"/>
      <Add DbType="DateTime" Name="end"/>
    </Parameters>
  </Operation>

  
</Unit>

=== davitp/tracking-software/trunk/TrackingSoftware/AccessLayer/MappingResources/SQLUnitMapping/car_operations.xml
<?xml version="1.0" encoding="utf-8" ?>
<Unit UnitName="car" xmlns="http://www.w3schools.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.w3schools.com OperationsMapperSchema.xsd">
  
  <!-- GetAll operation have no parameters -->
  <Operation Name="GetAll">
    <CommandType>Text</CommandType>
    <CommandText>
      select id, color, manufacturer, model
      from cars_table
    </CommandText>
    <ReturnType>Set</ReturnType>
  </Operation>
  
    <!--Creation Operation -->
  <Operation Name="Create">
    <CommandType>Text</CommandType>
    <CommandText>
      insert into cars_table default values;
      select id, color, manufacturer, model
      from cars_table
      where 
      id = (select ident_current('cars_table'))
    </CommandText>
    <ReturnType>Set</ReturnType>
  </Operation>
  
  <!-- Get By Id operation -->
  <Operation Name="GetById">
    <CommandType>Text</CommandType>
    <CommandText>
      select id, color, manufacturer, model
      from cars_table
      where 
      id = @idParam;
    </CommandText>
    <ReturnType>Set</ReturnType>
    <Parameters>
      <Add DbType="Int" Name="idParam" />
    </Parameters>
  </Operation>

  
  <!-- Get car ID's for car emulating... DEBUGING -->
  <Operation Name="GetIDs">
    <CommandType>Text</CommandType>
    <CommandText>
      select id from cars_table;
    </CommandText>
    <ReturnType>Set</ReturnType>
  </Operation>
 
  
</Unit>
