=== davitp/tracking-software/trunk/TrackingSoftware/AccessLayer/MappingResources/EntitiesSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">
  
  <xs:element name="Entities">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Entity">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Property" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="BusinessName" use="required"/>
                      <xs:attribute type="xs:string" name="PlainName" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
                <xs:unique name="UniquePropertyKey">
                  <xs:selector xpath="Property" />
                  <xs:field xpath="@BusinessName" />
                </xs:unique>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="BusinessName" use="required"/>
            <xs:attribute type="xs:string" name="PlainName" use="required"/>
          </xs:complexType>
          <xs:unique name="UniqueEntityKey">
            <xs:selector xpath="Entity" />
            <xs:field xpath="@BusinessName" />
          </xs:unique>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="MappingType"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== davitp/tracking-software/trunk/TrackingSoftware/AccessLayer/MappingResources/Entities.xml
<?xml version="1.0" encoding="utf-8" ?>

<Entities MappingType="BL2DAL" xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com EntitiesSchema.xsd">

  <Entity BusinessName="Car" PlainName="car">
    <Property BusinessName="Id" PlainName="id" />
    <Property BusinessName="DriverId" PlainName="driverId" />
    <Property BusinessName="CarDeviceId" PlainName="carDeviceId" />
    <Property BusinessName="Color" PlainName="color" />
    <Property BusinessName="Manufacturer" PlainName="manufacturer" />
    <Property BusinessName="Model" PlainName="model" />
  </Entity> 

</Entities>

=== davitp/tracking-software/TrackingSoftware/WebApplication/MappingResources/Entities.xml
<?xml version="1.0" encoding="utf-8" ?>

<Entities MappingType="BL2DAL" xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com EntitiesSchema.xsd">

  <Entity BusinessName="Car" PlainName="car">
    <Property BusinessName="Id" PlainName="id" />
    <Property BusinessName="Color" PlainName="color" />
    <Property BusinessName="Manufacturer" PlainName="manufacturer" />
    <Property BusinessName="Model" PlainName="model" />
  </Entity>

  <Entity BusinessName="User" PlainName="user">
    <Property BusinessName="UserId" PlainName="id" />
    <Property BusinessName="Username"  PlainName="username" />
    <Property BusinessName="Password" PlainName="passwd" />
    <Property BusinessName="FullName" PlainName="fullname" />
  </Entity>

  <Entity BusinessName="CarState" PlainName="carState">
    <Property BusinessName="FuelLevel" PlainName="fuelLevel"  />
    <Property BusinessName="NeedToChangeOil" PlainName="changeOil" />
    <Property BusinessName="When" PlainName="stateTime" />
    <Property BusinessName="Speed" PlainName="speed" />
    <Property BusinessName="Latitude" PlainName="latitude" />
    <Property BusinessName="Longitude" PlainName="longitude" />
  </Entity>
  
</Entities>
